SympleNetworkUserBundle:
    resource: "@SympleNetworkUserBundle/Controller"
    type:     annotation
    prefix:   /
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_user_bundle:
  resource: "@SympleNetworkUserBundle/Resources/config/routing.yml"